INSERT INTO Ability (id, name) VALUES ('noability', 'No Ability');
INSERT INTO Ability (id, name) VALUES ('adaptability', 'Adaptability');
INSERT INTO Ability (id, name) VALUES ('aerilate', 'Aerilate');
INSERT INTO Ability (id, name) VALUES ('aftermath', 'Aftermath');
INSERT INTO Ability (id, name) VALUES ('airlock', 'Air Lock');
INSERT INTO Ability (id, name) VALUES ('analytic', 'Analytic');
INSERT INTO Ability (id, name) VALUES ('angerpoint', 'Anger Point');
INSERT INTO Ability (id, name) VALUES ('angershell', 'Anger Shell');
INSERT INTO Ability (id, name) VALUES ('anticipation', 'Anticipation');
INSERT INTO Ability (id, name) VALUES ('arenatrap', 'Arena Trap');
INSERT INTO Ability (id, name) VALUES ('armortail', 'Armor Tail');
INSERT INTO Ability (id, name) VALUES ('aromaveil', 'Aroma Veil');
INSERT INTO Ability (id, name) VALUES ('asoneglastrier', 'As One (Glastrier)');
INSERT INTO Ability (id, name) VALUES ('asonespectrier', 'As One (Spectrier)');
INSERT INTO Ability (id, name) VALUES ('aurabreak', 'Aura Break');
INSERT INTO Ability (id, name) VALUES ('baddreams', 'Bad Dreams');
INSERT INTO Ability (id, name) VALUES ('ballfetch', 'Ball Fetch');
INSERT INTO Ability (id, name) VALUES ('battery', 'Battery');
INSERT INTO Ability (id, name) VALUES ('battlearmor', 'Battle Armor');
INSERT INTO Ability (id, name) VALUES ('battlebond', 'Battle Bond');
INSERT INTO Ability (id, name) VALUES ('beadsofruin', 'Beads of Ruin');
INSERT INTO Ability (id, name) VALUES ('beastboost', 'Beast Boost');
INSERT INTO Ability (id, name) VALUES ('berserk', 'Berserk');
INSERT INTO Ability (id, name) VALUES ('bigpecks', 'Big Pecks');
INSERT INTO Ability (id, name) VALUES ('blaze', 'Blaze');
INSERT INTO Ability (id, name) VALUES ('bulletproof', 'Bulletproof');
INSERT INTO Ability (id, name) VALUES ('cheekpouch', 'Cheek Pouch');
INSERT INTO Ability (id, name) VALUES ('chillingneigh', 'Chilling Neigh');
INSERT INTO Ability (id, name) VALUES ('chlorophyll', 'Chlorophyll');
INSERT INTO Ability (id, name) VALUES ('clearbody', 'Clear Body');
INSERT INTO Ability (id, name) VALUES ('cloudnine', 'Cloud Nine');
INSERT INTO Ability (id, name) VALUES ('colorchange', 'Color Change');
INSERT INTO Ability (id, name) VALUES ('comatose', 'Comatose');
INSERT INTO Ability (id, name) VALUES ('commander', 'Commander');
INSERT INTO Ability (id, name) VALUES ('competitive', 'Competitive');
INSERT INTO Ability (id, name) VALUES ('compoundeyes', 'Compound Eyes');
INSERT INTO Ability (id, name) VALUES ('contrary', 'Contrary');
INSERT INTO Ability (id, name) VALUES ('corrosion', 'Corrosion');
INSERT INTO Ability (id, name) VALUES ('costar', 'Costar');
INSERT INTO Ability (id, name) VALUES ('cottondown', 'Cotton Down');
INSERT INTO Ability (id, name) VALUES ('cudchew', 'Cud Chew');
INSERT INTO Ability (id, name) VALUES ('curiousmedicine', 'Curious Medicine');
INSERT INTO Ability (id, name) VALUES ('cursedbody', 'Cursed Body');
INSERT INTO Ability (id, name) VALUES ('cutecharm', 'Cute Charm');
INSERT INTO Ability (id, name) VALUES ('damp', 'Damp');
INSERT INTO Ability (id, name) VALUES ('dancer', 'Dancer');
INSERT INTO Ability (id, name) VALUES ('darkaura', 'Dark Aura');
INSERT INTO Ability (id, name) VALUES ('dauntlessshield', 'Dauntless Shield');
INSERT INTO Ability (id, name) VALUES ('dazzling', 'Dazzling');
INSERT INTO Ability (id, name) VALUES ('defeatist', 'Defeatist');
INSERT INTO Ability (id, name) VALUES ('defiant', 'Defiant');
INSERT INTO Ability (id, name) VALUES ('deltastream', 'Delta Stream');
INSERT INTO Ability (id, name) VALUES ('desolateland', 'Desolate Land');
INSERT INTO Ability (id, name) VALUES ('disguise', 'Disguise');
INSERT INTO Ability (id, name) VALUES ('download', 'Download');
INSERT INTO Ability (id, name) VALUES ('dragonsmaw', 'Dragon's Maw');
INSERT INTO Ability (id, name) VALUES ('drizzle', 'Drizzle');
INSERT INTO Ability (id, name) VALUES ('drought', 'Drought');
INSERT INTO Ability (id, name) VALUES ('dryskin', 'Dry Skin');
INSERT INTO Ability (id, name) VALUES ('earlybird', 'Early Bird');
INSERT INTO Ability (id, name) VALUES ('eartheater', 'Earth Eater');
INSERT INTO Ability (id, name) VALUES ('effectspore', 'Effect Spore');
INSERT INTO Ability (id, name) VALUES ('electricsurge', 'Electric Surge');
INSERT INTO Ability (id, name) VALUES ('electromorphosis', 'Electromorphosis');
INSERT INTO Ability (id, name) VALUES ('embodyaspectcornerstone', 'Embody Aspect (Cornerstone)');
INSERT INTO Ability (id, name) VALUES ('embodyaspecthearthflame', 'Embody Aspect (Hearthflame)');
INSERT INTO Ability (id, name) VALUES ('embodyaspectteal', 'Embody Aspect (Teal)');
INSERT INTO Ability (id, name) VALUES ('embodyaspectwellspring', 'Embody Aspect (Wellspring)');
INSERT INTO Ability (id, name) VALUES ('emergencyexit', 'Emergency Exit');
INSERT INTO Ability (id, name) VALUES ('fairyaura', 'Fairy Aura');
INSERT INTO Ability (id, name) VALUES ('filter', 'Filter');
INSERT INTO Ability (id, name) VALUES ('flamebody', 'Flame Body');
INSERT INTO Ability (id, name) VALUES ('flareboost', 'Flare Boost');
INSERT INTO Ability (id, name) VALUES ('flashfire', 'Flash Fire');
INSERT INTO Ability (id, name) VALUES ('flowergift', 'Flower Gift');
INSERT INTO Ability (id, name) VALUES ('flowerveil', 'Flower Veil');
INSERT INTO Ability (id, name) VALUES ('fluffy', 'Fluffy');
INSERT INTO Ability (id, name) VALUES ('forecast', 'Forecast');
INSERT INTO Ability (id, name) VALUES ('forewarn', 'Forewarn');
INSERT INTO Ability (id, name) VALUES ('friendguard', 'Friend Guard');
INSERT INTO Ability (id, name) VALUES ('frisk', 'Frisk');
INSERT INTO Ability (id, name) VALUES ('fullmetalbody', 'Full Metal Body');
INSERT INTO Ability (id, name) VALUES ('furcoat', 'Fur Coat');
INSERT INTO Ability (id, name) VALUES ('galewings', 'Gale Wings');
INSERT INTO Ability (id, name) VALUES ('galvanize', 'Galvanize');
INSERT INTO Ability (id, name) VALUES ('gluttony', 'Gluttony');
INSERT INTO Ability (id, name) VALUES ('goodasgold', 'Good as Gold');
INSERT INTO Ability (id, name) VALUES ('gooey', 'Gooey');
INSERT INTO Ability (id, name) VALUES ('gorillatactics', 'Gorilla Tactics');
INSERT INTO Ability (id, name) VALUES ('grasspelt', 'Grass Pelt');
INSERT INTO Ability (id, name) VALUES ('grassysurge', 'Grassy Surge');
INSERT INTO Ability (id, name) VALUES ('grimneigh', 'Grim Neigh');
INSERT INTO Ability (id, name) VALUES ('guarddog', 'Guard Dog');
INSERT INTO Ability (id, name) VALUES ('gulpmissile', 'Gulp Missile');
INSERT INTO Ability (id, name) VALUES ('guts', 'Guts');
INSERT INTO Ability (id, name) VALUES ('hadronengine', 'Hadron Engine');
INSERT INTO Ability (id, name) VALUES ('harvest', 'Harvest');
INSERT INTO Ability (id, name) VALUES ('healer', 'Healer');
INSERT INTO Ability (id, name) VALUES ('heatproof', 'Heatproof');
INSERT INTO Ability (id, name) VALUES ('heavymetal', 'Heavy Metal');
INSERT INTO Ability (id, name) VALUES ('honeygather', 'Honey Gather');
INSERT INTO Ability (id, name) VALUES ('hospitality', 'Hospitality');
INSERT INTO Ability (id, name) VALUES ('hugepower', 'Huge Power');
INSERT INTO Ability (id, name) VALUES ('hungerswitch', 'Hunger Switch');
INSERT INTO Ability (id, name) VALUES ('hustle', 'Hustle');
INSERT INTO Ability (id, name) VALUES ('hydration', 'Hydration');
INSERT INTO Ability (id, name) VALUES ('hypercutter', 'Hyper Cutter');
INSERT INTO Ability (id, name) VALUES ('icebody', 'Ice Body');
INSERT INTO Ability (id, name) VALUES ('iceface', 'Ice Face');
INSERT INTO Ability (id, name) VALUES ('icescales', 'Ice Scales');
INSERT INTO Ability (id, name) VALUES ('illuminate', 'Illuminate');
INSERT INTO Ability (id, name) VALUES ('illusion', 'Illusion');
INSERT INTO Ability (id, name) VALUES ('immunity', 'Immunity');
INSERT INTO Ability (id, name) VALUES ('imposter', 'Imposter');
INSERT INTO Ability (id, name) VALUES ('infiltrator', 'Infiltrator');
INSERT INTO Ability (id, name) VALUES ('innardsout', 'Innards Out');
INSERT INTO Ability (id, name) VALUES ('innerfocus', 'Inner Focus');
INSERT INTO Ability (id, name) VALUES ('insomnia', 'Insomnia');
INSERT INTO Ability (id, name) VALUES ('intimidate', 'Intimidate');
INSERT INTO Ability (id, name) VALUES ('intrepidsword', 'Intrepid Sword');
INSERT INTO Ability (id, name) VALUES ('ironbarbs', 'Iron Barbs');
INSERT INTO Ability (id, name) VALUES ('ironfist', 'Iron Fist');
INSERT INTO Ability (id, name) VALUES ('justified', 'Justified');
INSERT INTO Ability (id, name) VALUES ('keeneye', 'Keen Eye');
INSERT INTO Ability (id, name) VALUES ('klutz', 'Klutz');
INSERT INTO Ability (id, name) VALUES ('leafguard', 'Leaf Guard');
INSERT INTO Ability (id, name) VALUES ('levitate', 'Levitate');
INSERT INTO Ability (id, name) VALUES ('libero', 'Libero');
INSERT INTO Ability (id, name) VALUES ('lightmetal', 'Light Metal');
INSERT INTO Ability (id, name) VALUES ('lightningrod', 'Lightning Rod');
INSERT INTO Ability (id, name) VALUES ('limber', 'Limber');
INSERT INTO Ability (id, name) VALUES ('lingeringaroma', 'Lingering Aroma');
INSERT INTO Ability (id, name) VALUES ('liquidooze', 'Liquid Ooze');
INSERT INTO Ability (id, name) VALUES ('liquidvoice', 'Liquid Voice');
INSERT INTO Ability (id, name) VALUES ('longreach', 'Long Reach');
INSERT INTO Ability (id, name) VALUES ('magicbounce', 'Magic Bounce');
INSERT INTO Ability (id, name) VALUES ('magicguard', 'Magic Guard');
INSERT INTO Ability (id, name) VALUES ('magician', 'Magician');
INSERT INTO Ability (id, name) VALUES ('magmaarmor', 'Magma Armor');
INSERT INTO Ability (id, name) VALUES ('magnetpull', 'Magnet Pull');
INSERT INTO Ability (id, name) VALUES ('marvelscale', 'Marvel Scale');
INSERT INTO Ability (id, name) VALUES ('megalauncher', 'Mega Launcher');
INSERT INTO Ability (id, name) VALUES ('merciless', 'Merciless');
INSERT INTO Ability (id, name) VALUES ('mimicry', 'Mimicry');
INSERT INTO Ability (id, name) VALUES ('mindseye', 'Mind's Eye');
INSERT INTO Ability (id, name) VALUES ('minus', 'Minus');
INSERT INTO Ability (id, name) VALUES ('mirrorarmor', 'Mirror Armor');
INSERT INTO Ability (id, name) VALUES ('mistysurge', 'Misty Surge');
INSERT INTO Ability (id, name) VALUES ('moldbreaker', 'Mold Breaker');
INSERT INTO Ability (id, name) VALUES ('moody', 'Moody');
INSERT INTO Ability (id, name) VALUES ('motordrive', 'Motor Drive');
INSERT INTO Ability (id, name) VALUES ('moxie', 'Moxie');
INSERT INTO Ability (id, name) VALUES ('multiscale', 'Multiscale');
INSERT INTO Ability (id, name) VALUES ('multitype', 'Multitype');
INSERT INTO Ability (id, name) VALUES ('mummy', 'Mummy');
INSERT INTO Ability (id, name) VALUES ('myceliummight', 'Mycelium Might');
INSERT INTO Ability (id, name) VALUES ('naturalcure', 'Natural Cure');
INSERT INTO Ability (id, name) VALUES ('neuroforce', 'Neuroforce');
INSERT INTO Ability (id, name) VALUES ('neutralizinggas', 'Neutralizing Gas');
INSERT INTO Ability (id, name) VALUES ('noguard', 'No Guard');
INSERT INTO Ability (id, name) VALUES ('normalize', 'Normalize');
INSERT INTO Ability (id, name) VALUES ('oblivious', 'Oblivious');
INSERT INTO Ability (id, name) VALUES ('opportunist', 'Opportunist');
INSERT INTO Ability (id, name) VALUES ('orichalcumpulse', 'Orichalcum Pulse');
INSERT INTO Ability (id, name) VALUES ('overcoat', 'Overcoat');
INSERT INTO Ability (id, name) VALUES ('overgrow', 'Overgrow');
INSERT INTO Ability (id, name) VALUES ('owntempo', 'Own Tempo');
INSERT INTO Ability (id, name) VALUES ('parentalbond', 'Parental Bond');
INSERT INTO Ability (id, name) VALUES ('pastelveil', 'Pastel Veil');
INSERT INTO Ability (id, name) VALUES ('perishbody', 'Perish Body');
INSERT INTO Ability (id, name) VALUES ('pickpocket', 'Pickpocket');
INSERT INTO Ability (id, name) VALUES ('pickup', 'Pickup');
INSERT INTO Ability (id, name) VALUES ('pixilate', 'Pixilate');
INSERT INTO Ability (id, name) VALUES ('plus', 'Plus');
INSERT INTO Ability (id, name) VALUES ('poisonheal', 'Poison Heal');
INSERT INTO Ability (id, name) VALUES ('poisonpoint', 'Poison Point');
INSERT INTO Ability (id, name) VALUES ('poisonpuppeteer', 'Poison Puppeteer');
INSERT INTO Ability (id, name) VALUES ('poisontouch', 'Poison Touch');
INSERT INTO Ability (id, name) VALUES ('powerconstruct', 'Power Construct');
INSERT INTO Ability (id, name) VALUES ('powerofalchemy', 'Power of Alchemy');
INSERT INTO Ability (id, name) VALUES ('powerspot', 'Power Spot');
INSERT INTO Ability (id, name) VALUES ('prankster', 'Prankster');
INSERT INTO Ability (id, name) VALUES ('pressure', 'Pressure');
INSERT INTO Ability (id, name) VALUES ('primordialsea', 'Primordial Sea');
INSERT INTO Ability (id, name) VALUES ('prismarmor', 'Prism Armor');
INSERT INTO Ability (id, name) VALUES ('propellertail', 'Propeller Tail');
INSERT INTO Ability (id, name) VALUES ('protean', 'Protean');
INSERT INTO Ability (id, name) VALUES ('protosynthesis', 'Protosynthesis');
INSERT INTO Ability (id, name) VALUES ('psychicsurge', 'Psychic Surge');
INSERT INTO Ability (id, name) VALUES ('punkrock', 'Punk Rock');
INSERT INTO Ability (id, name) VALUES ('purepower', 'Pure Power');
INSERT INTO Ability (id, name) VALUES ('purifyingsalt', 'Purifying Salt');
INSERT INTO Ability (id, name) VALUES ('quarkdrive', 'Quark Drive');
INSERT INTO Ability (id, name) VALUES ('queenlymajesty', 'Queenly Majesty');
INSERT INTO Ability (id, name) VALUES ('quickdraw', 'Quick Draw');
INSERT INTO Ability (id, name) VALUES ('quickfeet', 'Quick Feet');
INSERT INTO Ability (id, name) VALUES ('raindish', 'Rain Dish');
INSERT INTO Ability (id, name) VALUES ('rattled', 'Rattled');
INSERT INTO Ability (id, name) VALUES ('receiver', 'Receiver');
INSERT INTO Ability (id, name) VALUES ('reckless', 'Reckless');
INSERT INTO Ability (id, name) VALUES ('refrigerate', 'Refrigerate');
INSERT INTO Ability (id, name) VALUES ('regenerator', 'Regenerator');
INSERT INTO Ability (id, name) VALUES ('ripen', 'Ripen');
INSERT INTO Ability (id, name) VALUES ('rivalry', 'Rivalry');
INSERT INTO Ability (id, name) VALUES ('rkssystem', 'RKS System');
INSERT INTO Ability (id, name) VALUES ('rockhead', 'Rock Head');
INSERT INTO Ability (id, name) VALUES ('rockypayload', 'Rocky Payload');
INSERT INTO Ability (id, name) VALUES ('roughskin', 'Rough Skin');
INSERT INTO Ability (id, name) VALUES ('runaway', 'Run Away');
INSERT INTO Ability (id, name) VALUES ('sandforce', 'Sand Force');
INSERT INTO Ability (id, name) VALUES ('sandrush', 'Sand Rush');
INSERT INTO Ability (id, name) VALUES ('sandspit', 'Sand Spit');
INSERT INTO Ability (id, name) VALUES ('sandstream', 'Sand Stream');
INSERT INTO Ability (id, name) VALUES ('sandveil', 'Sand Veil');
INSERT INTO Ability (id, name) VALUES ('sapsipper', 'Sap Sipper');
INSERT INTO Ability (id, name) VALUES ('schooling', 'Schooling');
INSERT INTO Ability (id, name) VALUES ('scrappy', 'Scrappy');
INSERT INTO Ability (id, name) VALUES ('screencleaner', 'Screen Cleaner');
INSERT INTO Ability (id, name) VALUES ('seedsower', 'Seed Sower');
INSERT INTO Ability (id, name) VALUES ('serenegrace', 'Serene Grace');
INSERT INTO Ability (id, name) VALUES ('shadowshield', 'Shadow Shield');
INSERT INTO Ability (id, name) VALUES ('shadowtag', 'Shadow Tag');
INSERT INTO Ability (id, name) VALUES ('sharpness', 'Sharpness');
INSERT INTO Ability (id, name) VALUES ('shedskin', 'Shed Skin');
INSERT INTO Ability (id, name) VALUES ('sheerforce', 'Sheer Force');
INSERT INTO Ability (id, name) VALUES ('shellarmor', 'Shell Armor');
INSERT INTO Ability (id, name) VALUES ('shielddust', 'Shield Dust');
INSERT INTO Ability (id, name) VALUES ('shieldsdown', 'Shields Down');
INSERT INTO Ability (id, name) VALUES ('simple', 'Simple');
INSERT INTO Ability (id, name) VALUES ('skilllink', 'Skill Link');
INSERT INTO Ability (id, name) VALUES ('slowstart', 'Slow Start');
INSERT INTO Ability (id, name) VALUES ('slushrush', 'Slush Rush');
INSERT INTO Ability (id, name) VALUES ('sniper', 'Sniper');
INSERT INTO Ability (id, name) VALUES ('snowcloak', 'Snow Cloak');
INSERT INTO Ability (id, name) VALUES ('snowwarning', 'Snow Warning');
INSERT INTO Ability (id, name) VALUES ('solarpower', 'Solar Power');
INSERT INTO Ability (id, name) VALUES ('solidrock', 'Solid Rock');
INSERT INTO Ability (id, name) VALUES ('soulheart', 'Soul-Heart');
INSERT INTO Ability (id, name) VALUES ('soundproof', 'Soundproof');
INSERT INTO Ability (id, name) VALUES ('speedboost', 'Speed Boost');
INSERT INTO Ability (id, name) VALUES ('stakeout', 'Stakeout');
INSERT INTO Ability (id, name) VALUES ('stall', 'Stall');
INSERT INTO Ability (id, name) VALUES ('stalwart', 'Stalwart');
INSERT INTO Ability (id, name) VALUES ('stamina', 'Stamina');
INSERT INTO Ability (id, name) VALUES ('stancechange', 'Stance Change');
INSERT INTO Ability (id, name) VALUES ('static', 'Static');
INSERT INTO Ability (id, name) VALUES ('steadfast', 'Steadfast');
INSERT INTO Ability (id, name) VALUES ('steamengine', 'Steam Engine');
INSERT INTO Ability (id, name) VALUES ('steelworker', 'Steelworker');
INSERT INTO Ability (id, name) VALUES ('steelyspirit', 'Steely Spirit');
INSERT INTO Ability (id, name) VALUES ('stench', 'Stench');
INSERT INTO Ability (id, name) VALUES ('stickyhold', 'Sticky Hold');
INSERT INTO Ability (id, name) VALUES ('stormdrain', 'Storm Drain');
INSERT INTO Ability (id, name) VALUES ('strongjaw', 'Strong Jaw');
INSERT INTO Ability (id, name) VALUES ('sturdy', 'Sturdy');
INSERT INTO Ability (id, name) VALUES ('suctioncups', 'Suction Cups');
INSERT INTO Ability (id, name) VALUES ('superluck', 'Super Luck');
INSERT INTO Ability (id, name) VALUES ('supersweetsyrup', 'Supersweet Syrup');
INSERT INTO Ability (id, name) VALUES ('supremeoverlord', 'Supreme Overlord');
INSERT INTO Ability (id, name) VALUES ('surgesurfer', 'Surge Surfer');
INSERT INTO Ability (id, name) VALUES ('swarm', 'Swarm');
INSERT INTO Ability (id, name) VALUES ('sweetveil', 'Sweet Veil');
INSERT INTO Ability (id, name) VALUES ('swiftswim', 'Swift Swim');
INSERT INTO Ability (id, name) VALUES ('symbiosis', 'Symbiosis');
INSERT INTO Ability (id, name) VALUES ('synchronize', 'Synchronize');
INSERT INTO Ability (id, name) VALUES ('swordofruin', 'Sword of Ruin');
INSERT INTO Ability (id, name) VALUES ('tabletsofruin', 'Tablets of Ruin');
INSERT INTO Ability (id, name) VALUES ('tangledfeet', 'Tangled Feet');
INSERT INTO Ability (id, name) VALUES ('tanglinghair', 'Tangling Hair');
INSERT INTO Ability (id, name) VALUES ('technician', 'Technician');
INSERT INTO Ability (id, name) VALUES ('telepathy', 'Telepathy');
INSERT INTO Ability (id, name) VALUES ('teraformzero', 'Teraform Zero');
INSERT INTO Ability (id, name) VALUES ('terashell', 'Tera Shell');
INSERT INTO Ability (id, name) VALUES ('terashift', 'Tera Shift');
INSERT INTO Ability (id, name) VALUES ('teravolt', 'Teravolt');
INSERT INTO Ability (id, name) VALUES ('thermalexchange', 'Thermal Exchange');
INSERT INTO Ability (id, name) VALUES ('thickfat', 'Thick Fat');
INSERT INTO Ability (id, name) VALUES ('tintedlens', 'Tinted Lens');
INSERT INTO Ability (id, name) VALUES ('torrent', 'Torrent');
INSERT INTO Ability (id, name) VALUES ('toughclaws', 'Tough Claws');
INSERT INTO Ability (id, name) VALUES ('toxicboost', 'Toxic Boost');
INSERT INTO Ability (id, name) VALUES ('toxicchain', 'Toxic Chain');
INSERT INTO Ability (id, name) VALUES ('toxicdebris', 'Toxic Debris');
INSERT INTO Ability (id, name) VALUES ('trace', 'Trace');
INSERT INTO Ability (id, name) VALUES ('transistor', 'Transistor');
INSERT INTO Ability (id, name) VALUES ('triage', 'Triage');
INSERT INTO Ability (id, name) VALUES ('truant', 'Truant');
INSERT INTO Ability (id, name) VALUES ('turboblaze', 'Turboblaze');
INSERT INTO Ability (id, name) VALUES ('unaware', 'Unaware');
INSERT INTO Ability (id, name) VALUES ('unburden', 'Unburden');
INSERT INTO Ability (id, name) VALUES ('unnerve', 'Unnerve');
INSERT INTO Ability (id, name) VALUES ('unseenfist', 'Unseen Fist');
INSERT INTO Ability (id, name) VALUES ('vesselofruin', 'Vessel of Ruin');
INSERT INTO Ability (id, name) VALUES ('victorystar', 'Victory Star');
INSERT INTO Ability (id, name) VALUES ('vitalspirit', 'Vital Spirit');
INSERT INTO Ability (id, name) VALUES ('voltabsorb', 'Volt Absorb');
INSERT INTO Ability (id, name) VALUES ('wanderingspirit', 'Wandering Spirit');
INSERT INTO Ability (id, name) VALUES ('waterabsorb', 'Water Absorb');
INSERT INTO Ability (id, name) VALUES ('waterbubble', 'Water Bubble');
INSERT INTO Ability (id, name) VALUES ('watercompaction', 'Water Compaction');
INSERT INTO Ability (id, name) VALUES ('waterveil', 'Water Veil');
INSERT INTO Ability (id, name) VALUES ('weakarmor', 'Weak Armor');
INSERT INTO Ability (id, name) VALUES ('wellbakedbody', 'Well-Baked Body');
INSERT INTO Ability (id, name) VALUES ('whitesmoke', 'White Smoke');
INSERT INTO Ability (id, name) VALUES ('wimpout', 'Wimp Out');
INSERT INTO Ability (id, name) VALUES ('windpower', 'Wind Power');
INSERT INTO Ability (id, name) VALUES ('windrider', 'Wind Rider');
INSERT INTO Ability (id, name) VALUES ('wonderguard', 'Wonder Guard');
INSERT INTO Ability (id, name) VALUES ('wonderskin', 'Wonder Skin');
INSERT INTO Ability (id, name) VALUES ('zenmode', 'Zen Mode');
INSERT INTO Ability (id, name) VALUES ('zerotohero', 'Zero to Hero');
INSERT INTO Ability (id, name) VALUES ('mountaineer', 'Mountaineer');
INSERT INTO Ability (id, name) VALUES ('rebound', 'Rebound');
INSERT INTO Ability (id, name) VALUES ('persistent', 'Persistent');
