INSERT INTO Item (id, name) VALUES ('nothing', 'No Item');
INSERT INTO Item (id, name) VALUES ('abilityshield', 'Ability Shield');
INSERT INTO Item (id, name) VALUES ('abomasite', 'Abomasite');
INSERT INTO Item (id, name) VALUES ('absolite', 'Absolite');
INSERT INTO Item (id, name) VALUES ('absorbbulb', 'Absorb Bulb');
INSERT INTO Item (id, name) VALUES ('adamantcrystal', 'Adamant Crystal');
INSERT INTO Item (id, name) VALUES ('adamantorb', 'Adamant Orb');
INSERT INTO Item (id, name) VALUES ('adrenalineorb', 'Adrenaline Orb');
INSERT INTO Item (id, name) VALUES ('aerodactylite', 'Aerodactylite');
INSERT INTO Item (id, name) VALUES ('aggronite', 'Aggronite');
INSERT INTO Item (id, name) VALUES ('aguavberry', 'Aguav Berry');
INSERT INTO Item (id, name) VALUES ('airballoon', 'Air Balloon');
INSERT INTO Item (id, name) VALUES ('alakazite', 'Alakazite');
INSERT INTO Item (id, name) VALUES ('aloraichiumz', 'Aloraichium Z');
INSERT INTO Item (id, name) VALUES ('altarianite', 'Altarianite');
INSERT INTO Item (id, name) VALUES ('ampharosite', 'Ampharosite');
INSERT INTO Item (id, name) VALUES ('apicotberry', 'Apicot Berry');
INSERT INTO Item (id, name) VALUES ('armorfossil', 'Armor Fossil');
INSERT INTO Item (id, name) VALUES ('aspearberry', 'Aspear Berry');
INSERT INTO Item (id, name) VALUES ('assaultvest', 'Assault Vest');
INSERT INTO Item (id, name) VALUES ('audinite', 'Audinite');
INSERT INTO Item (id, name) VALUES ('auspiciousarmor', 'Auspicious Armor');
INSERT INTO Item (id, name) VALUES ('babiriberry', 'Babiri Berry');
INSERT INTO Item (id, name) VALUES ('banettite', 'Banettite');
INSERT INTO Item (id, name) VALUES ('beastball', 'Beast Ball');
INSERT INTO Item (id, name) VALUES ('beedrillite', 'Beedrillite');
INSERT INTO Item (id, name) VALUES ('belueberry', 'Belue Berry');
INSERT INTO Item (id, name) VALUES ('berryjuice', 'Berry Juice');
INSERT INTO Item (id, name) VALUES ('berrysweet', 'Berry Sweet');
INSERT INTO Item (id, name) VALUES ('bignugget', 'Big Nugget');
INSERT INTO Item (id, name) VALUES ('bigroot', 'Big Root');
INSERT INTO Item (id, name) VALUES ('bindingband', 'Binding Band');
INSERT INTO Item (id, name) VALUES ('blackbelt', 'Black Belt');
INSERT INTO Item (id, name) VALUES ('blackglasses', 'Black Glasses');
INSERT INTO Item (id, name) VALUES ('blacksludge', 'Black Sludge');
INSERT INTO Item (id, name) VALUES ('blastoisinite', 'Blastoisinite');
INSERT INTO Item (id, name) VALUES ('blazikenite', 'Blazikenite');
INSERT INTO Item (id, name) VALUES ('blueorb', 'Blue Orb');
INSERT INTO Item (id, name) VALUES ('blukberry', 'Bluk Berry');
INSERT INTO Item (id, name) VALUES ('blunderpolicy', 'Blunder Policy');
INSERT INTO Item (id, name) VALUES ('boosterenergy', 'Booster Energy');
INSERT INTO Item (id, name) VALUES ('bottlecap', 'Bottle Cap');
INSERT INTO Item (id, name) VALUES ('brightpowder', 'Bright Powder');
INSERT INTO Item (id, name) VALUES ('buggem', 'Bug Gem');
INSERT INTO Item (id, name) VALUES ('bugmemory', 'Bug Memory');
INSERT INTO Item (id, name) VALUES ('buginiumz', 'Buginium Z');
INSERT INTO Item (id, name) VALUES ('burndrive', 'Burn Drive');
INSERT INTO Item (id, name) VALUES ('cameruptite', 'Cameruptite');
INSERT INTO Item (id, name) VALUES ('cellbattery', 'Cell Battery');
INSERT INTO Item (id, name) VALUES ('charcoal', 'Charcoal');
INSERT INTO Item (id, name) VALUES ('charizarditex', 'Charizardite X');
INSERT INTO Item (id, name) VALUES ('charizarditey', 'Charizardite Y');
INSERT INTO Item (id, name) VALUES ('chartiberry', 'Charti Berry');
INSERT INTO Item (id, name) VALUES ('cheriberry', 'Cheri Berry');
INSERT INTO Item (id, name) VALUES ('cherishball', 'Cherish Ball');
INSERT INTO Item (id, name) VALUES ('chestoberry', 'Chesto Berry');
INSERT INTO Item (id, name) VALUES ('chilanberry', 'Chilan Berry');
INSERT INTO Item (id, name) VALUES ('chilldrive', 'Chill Drive');
INSERT INTO Item (id, name) VALUES ('chippedpot', 'Chipped Pot');
INSERT INTO Item (id, name) VALUES ('choiceband', 'Choice Band');
INSERT INTO Item (id, name) VALUES ('choicescarf', 'Choice Scarf');
INSERT INTO Item (id, name) VALUES ('choicespecs', 'Choice Specs');
INSERT INTO Item (id, name) VALUES ('chopleberry', 'Chople Berry');
INSERT INTO Item (id, name) VALUES ('clawfossil', 'Claw Fossil');
INSERT INTO Item (id, name) VALUES ('clearamulet', 'Clear Amulet');
INSERT INTO Item (id, name) VALUES ('cloversweet', 'Clover Sweet');
INSERT INTO Item (id, name) VALUES ('cobaberry', 'Coba Berry');
INSERT INTO Item (id, name) VALUES ('colburberry', 'Colbur Berry');
INSERT INTO Item (id, name) VALUES ('cornerstonemask', 'Cornerstone Mask');
INSERT INTO Item (id, name) VALUES ('cornnberry', 'Cornn Berry');
INSERT INTO Item (id, name) VALUES ('coverfossil', 'Cover Fossil');
INSERT INTO Item (id, name) VALUES ('covertcloak', 'Covert Cloak');
INSERT INTO Item (id, name) VALUES ('crackedpot', 'Cracked Pot');
INSERT INTO Item (id, name) VALUES ('custapberry', 'Custap Berry');
INSERT INTO Item (id, name) VALUES ('damprock', 'Damp Rock');
INSERT INTO Item (id, name) VALUES ('darkgem', 'Dark Gem');
INSERT INTO Item (id, name) VALUES ('darkmemory', 'Dark Memory');
INSERT INTO Item (id, name) VALUES ('darkiniumz', 'Darkinium Z');
INSERT INTO Item (id, name) VALUES ('dawnstone', 'Dawn Stone');
INSERT INTO Item (id, name) VALUES ('decidiumz', 'Decidium Z');
INSERT INTO Item (id, name) VALUES ('deepseascale', 'Deep Sea Scale');
INSERT INTO Item (id, name) VALUES ('deepseatooth', 'Deep Sea Tooth');
INSERT INTO Item (id, name) VALUES ('destinyknot', 'Destiny Knot');
INSERT INTO Item (id, name) VALUES ('diancite', 'Diancite');
INSERT INTO Item (id, name) VALUES ('diveball', 'Dive Ball');
INSERT INTO Item (id, name) VALUES ('domefossil', 'Dome Fossil');
INSERT INTO Item (id, name) VALUES ('dousedrive', 'Douse Drive');
INSERT INTO Item (id, name) VALUES ('dracoplate', 'Draco Plate');
INSERT INTO Item (id, name) VALUES ('dragonfang', 'Dragon Fang');
INSERT INTO Item (id, name) VALUES ('dragongem', 'Dragon Gem');
INSERT INTO Item (id, name) VALUES ('dragonmemory', 'Dragon Memory');
INSERT INTO Item (id, name) VALUES ('dragonscale', 'Dragon Scale');
INSERT INTO Item (id, name) VALUES ('dragoniumz', 'Dragonium Z');
INSERT INTO Item (id, name) VALUES ('dreadplate', 'Dread Plate');
INSERT INTO Item (id, name) VALUES ('dreamball', 'Dream Ball');
INSERT INTO Item (id, name) VALUES ('dubiousdisc', 'Dubious Disc');
INSERT INTO Item (id, name) VALUES ('durinberry', 'Durin Berry');
INSERT INTO Item (id, name) VALUES ('duskball', 'Dusk Ball');
INSERT INTO Item (id, name) VALUES ('duskstone', 'Dusk Stone');
INSERT INTO Item (id, name) VALUES ('earthplate', 'Earth Plate');
INSERT INTO Item (id, name) VALUES ('eeviumz', 'Eevium Z');
INSERT INTO Item (id, name) VALUES ('ejectbutton', 'Eject Button');
INSERT INTO Item (id, name) VALUES ('ejectpack', 'Eject Pack');
INSERT INTO Item (id, name) VALUES ('electirizer', 'Electirizer');
INSERT INTO Item (id, name) VALUES ('electricgem', 'Electric Gem');
INSERT INTO Item (id, name) VALUES ('electricmemory', 'Electric Memory');
INSERT INTO Item (id, name) VALUES ('electricseed', 'Electric Seed');
INSERT INTO Item (id, name) VALUES ('electriumz', 'Electrium Z');
INSERT INTO Item (id, name) VALUES ('enigmaberry', 'Enigma Berry');
INSERT INTO Item (id, name) VALUES ('eviolite', 'Eviolite');
INSERT INTO Item (id, name) VALUES ('expertbelt', 'Expert Belt');
INSERT INTO Item (id, name) VALUES ('fairiumz', 'Fairium Z');
INSERT INTO Item (id, name) VALUES ('fairyfeather', 'Fairy Feather');
INSERT INTO Item (id, name) VALUES ('fairygem', 'Fairy Gem');
INSERT INTO Item (id, name) VALUES ('fairymemory', 'Fairy Memory');
INSERT INTO Item (id, name) VALUES ('fastball', 'Fast Ball');
INSERT INTO Item (id, name) VALUES ('fightinggem', 'Fighting Gem');
INSERT INTO Item (id, name) VALUES ('fightingmemory', 'Fighting Memory');
INSERT INTO Item (id, name) VALUES ('fightiniumz', 'Fightinium Z');
INSERT INTO Item (id, name) VALUES ('figyberry', 'Figy Berry');
INSERT INTO Item (id, name) VALUES ('firegem', 'Fire Gem');
INSERT INTO Item (id, name) VALUES ('firememory', 'Fire Memory');
INSERT INTO Item (id, name) VALUES ('firestone', 'Fire Stone');
INSERT INTO Item (id, name) VALUES ('firiumz', 'Firium Z');
INSERT INTO Item (id, name) VALUES ('fistplate', 'Fist Plate');
INSERT INTO Item (id, name) VALUES ('flameorb', 'Flame Orb');
INSERT INTO Item (id, name) VALUES ('flameplate', 'Flame Plate');
INSERT INTO Item (id, name) VALUES ('floatstone', 'Float Stone');
INSERT INTO Item (id, name) VALUES ('flowersweet', 'Flower Sweet');
INSERT INTO Item (id, name) VALUES ('flyinggem', 'Flying Gem');
INSERT INTO Item (id, name) VALUES ('flyingmemory', 'Flying Memory');
INSERT INTO Item (id, name) VALUES ('flyiniumz', 'Flyinium Z');
INSERT INTO Item (id, name) VALUES ('focusband', 'Focus Band');
INSERT INTO Item (id, name) VALUES ('focussash', 'Focus Sash');
INSERT INTO Item (id, name) VALUES ('fossilizedbird', 'Fossilized Bird');
INSERT INTO Item (id, name) VALUES ('fossilizeddino', 'Fossilized Dino');
INSERT INTO Item (id, name) VALUES ('fossilizeddrake', 'Fossilized Drake');
INSERT INTO Item (id, name) VALUES ('fossilizedfish', 'Fossilized Fish');
INSERT INTO Item (id, name) VALUES ('friendball', 'Friend Ball');
INSERT INTO Item (id, name) VALUES ('fullincense', 'Full Incense');
INSERT INTO Item (id, name) VALUES ('galaricacuff', 'Galarica Cuff');
INSERT INTO Item (id, name) VALUES ('galaricawreath', 'Galarica Wreath');
INSERT INTO Item (id, name) VALUES ('galladite', 'Galladite');
INSERT INTO Item (id, name) VALUES ('ganlonberry', 'Ganlon Berry');
INSERT INTO Item (id, name) VALUES ('garchompite', 'Garchompite');
INSERT INTO Item (id, name) VALUES ('gardevoirite', 'Gardevoirite');
INSERT INTO Item (id, name) VALUES ('gengarite', 'Gengarite');
INSERT INTO Item (id, name) VALUES ('ghostgem', 'Ghost Gem');
INSERT INTO Item (id, name) VALUES ('ghostmemory', 'Ghost Memory');
INSERT INTO Item (id, name) VALUES ('ghostiumz', 'Ghostium Z');
INSERT INTO Item (id, name) VALUES ('glalitite', 'Glalitite');
INSERT INTO Item (id, name) VALUES ('goldbottlecap', 'Gold Bottle Cap');
INSERT INTO Item (id, name) VALUES ('grassgem', 'Grass Gem');
INSERT INTO Item (id, name) VALUES ('grassmemory', 'Grass Memory');
INSERT INTO Item (id, name) VALUES ('grassiumz', 'Grassium Z');
INSERT INTO Item (id, name) VALUES ('grassyseed', 'Grassy Seed');
INSERT INTO Item (id, name) VALUES ('greatball', 'Great Ball');
INSERT INTO Item (id, name) VALUES ('grepaberry', 'Grepa Berry');
INSERT INTO Item (id, name) VALUES ('gripclaw', 'Grip Claw');
INSERT INTO Item (id, name) VALUES ('griseouscore', 'Griseous Core');
INSERT INTO Item (id, name) VALUES ('griseousorb', 'Griseous Orb');
INSERT INTO Item (id, name) VALUES ('groundgem', 'Ground Gem');
INSERT INTO Item (id, name) VALUES ('groundmemory', 'Ground Memory');
INSERT INTO Item (id, name) VALUES ('groundiumz', 'Groundium Z');
INSERT INTO Item (id, name) VALUES ('gyaradosite', 'Gyaradosite');
INSERT INTO Item (id, name) VALUES ('habanberry', 'Haban Berry');
INSERT INTO Item (id, name) VALUES ('hardstone', 'Hard Stone');
INSERT INTO Item (id, name) VALUES ('healball', 'Heal Ball');
INSERT INTO Item (id, name) VALUES ('hearthflamemask', 'Hearthflame Mask');
INSERT INTO Item (id, name) VALUES ('heatrock', 'Heat Rock');
INSERT INTO Item (id, name) VALUES ('heavyball', 'Heavy Ball');
INSERT INTO Item (id, name) VALUES ('heavydutyboots', 'Heavy-Duty Boots');
INSERT INTO Item (id, name) VALUES ('helixfossil', 'Helix Fossil');
INSERT INTO Item (id, name) VALUES ('heracronite', 'Heracronite');
INSERT INTO Item (id, name) VALUES ('hondewberry', 'Hondew Berry');
INSERT INTO Item (id, name) VALUES ('houndoominite', 'Houndoominite');
INSERT INTO Item (id, name) VALUES ('iapapaberry', 'Iapapa Berry');
INSERT INTO Item (id, name) VALUES ('icegem', 'Ice Gem');
INSERT INTO Item (id, name) VALUES ('icememory', 'Ice Memory');
INSERT INTO Item (id, name) VALUES ('icestone', 'Ice Stone');
INSERT INTO Item (id, name) VALUES ('icicleplate', 'Icicle Plate');
INSERT INTO Item (id, name) VALUES ('iciumz', 'Icium Z');
INSERT INTO Item (id, name) VALUES ('icyrock', 'Icy Rock');
INSERT INTO Item (id, name) VALUES ('inciniumz', 'Incinium Z');
INSERT INTO Item (id, name) VALUES ('insectplate', 'Insect Plate');
INSERT INTO Item (id, name) VALUES ('ironball', 'Iron Ball');
INSERT INTO Item (id, name) VALUES ('ironplate', 'Iron Plate');
INSERT INTO Item (id, name) VALUES ('jabocaberry', 'Jaboca Berry');
INSERT INTO Item (id, name) VALUES ('jawfossil', 'Jaw Fossil');
INSERT INTO Item (id, name) VALUES ('kasibberry', 'Kasib Berry');
INSERT INTO Item (id, name) VALUES ('kebiaberry', 'Kebia Berry');
INSERT INTO Item (id, name) VALUES ('keeberry', 'Kee Berry');
INSERT INTO Item (id, name) VALUES ('kelpsyberry', 'Kelpsy Berry');
INSERT INTO Item (id, name) VALUES ('kangaskhanite', 'Kangaskhanite');
INSERT INTO Item (id, name) VALUES ('kingsrock', 'King''s Rock');
INSERT INTO Item (id, name) VALUES ('kommoniumz', 'Kommonium Z');
INSERT INTO Item (id, name) VALUES ('laggingtail', 'Lagging Tail');
INSERT INTO Item (id, name) VALUES ('lansatberry', 'Lansat Berry');
INSERT INTO Item (id, name) VALUES ('latiasite', 'Latiasite');
INSERT INTO Item (id, name) VALUES ('latiosite', 'Latiosite');
INSERT INTO Item (id, name) VALUES ('laxincense', 'Lax Incense');
INSERT INTO Item (id, name) VALUES ('leafstone', 'Leaf Stone');
INSERT INTO Item (id, name) VALUES ('leek', 'Leek');
INSERT INTO Item (id, name) VALUES ('leftovers', 'Leftovers');
INSERT INTO Item (id, name) VALUES ('leppaberry', 'Leppa Berry');
INSERT INTO Item (id, name) VALUES ('levelball', 'Level Ball');
INSERT INTO Item (id, name) VALUES ('liechiberry', 'Liechi Berry');
INSERT INTO Item (id, name) VALUES ('lifeorb', 'Life Orb');
INSERT INTO Item (id, name) VALUES ('lightball', 'Light Ball');
INSERT INTO Item (id, name) VALUES ('lightclay', 'Light Clay');
INSERT INTO Item (id, name) VALUES ('loadeddice', 'Loaded Dice');
INSERT INTO Item (id, name) VALUES ('lopunnite', 'Lopunnite');
INSERT INTO Item (id, name) VALUES ('loveball', 'Love Ball');
INSERT INTO Item (id, name) VALUES ('lovesweet', 'Love Sweet');
INSERT INTO Item (id, name) VALUES ('lucarionite', 'Lucarionite');
INSERT INTO Item (id, name) VALUES ('luckypunch', 'Lucky Punch');
INSERT INTO Item (id, name) VALUES ('lumberry', 'Lum Berry');
INSERT INTO Item (id, name) VALUES ('luminousmoss', 'Luminous Moss');
INSERT INTO Item (id, name) VALUES ('lunaliumz', 'Lunalium Z');
INSERT INTO Item (id, name) VALUES ('lureball', 'Lure Ball');
INSERT INTO Item (id, name) VALUES ('lustrousglobe', 'Lustrous Globe');
INSERT INTO Item (id, name) VALUES ('lustrousorb', 'Lustrous Orb');
INSERT INTO Item (id, name) VALUES ('luxuryball', 'Luxury Ball');
INSERT INTO Item (id, name) VALUES ('lycaniumz', 'Lycanium Z');
INSERT INTO Item (id, name) VALUES ('machobrace', 'Macho Brace');
INSERT INTO Item (id, name) VALUES ('magmarizer', 'Magmarizer');
INSERT INTO Item (id, name) VALUES ('magnet', 'Magnet');
INSERT INTO Item (id, name) VALUES ('magoberry', 'Mago Berry');
INSERT INTO Item (id, name) VALUES ('magostberry', 'Magost Berry');
INSERT INTO Item (id, name) VALUES ('mail', 'Mail');
INSERT INTO Item (id, name) VALUES ('maliciousarmor', 'Malicious Armor');
INSERT INTO Item (id, name) VALUES ('manectite', 'Manectite');
INSERT INTO Item (id, name) VALUES ('marangaberry', 'Maranga Berry');
INSERT INTO Item (id, name) VALUES ('marshadiumz', 'Marshadium Z');
INSERT INTO Item (id, name) VALUES ('masterball', 'Master Ball');
INSERT INTO Item (id, name) VALUES ('masterpieceteacup', 'Masterpiece Teacup');
INSERT INTO Item (id, name) VALUES ('mawilite', 'Mawilite');
INSERT INTO Item (id, name) VALUES ('meadowplate', 'Meadow Plate');
INSERT INTO Item (id, name) VALUES ('medichamite', 'Medichamite');
INSERT INTO Item (id, name) VALUES ('mentalherb', 'Mental Herb');
INSERT INTO Item (id, name) VALUES ('metagrossite', 'Metagrossite');
INSERT INTO Item (id, name) VALUES ('metalalloy', 'Metal Alloy');
INSERT INTO Item (id, name) VALUES ('metalcoat', 'Metal Coat');
INSERT INTO Item (id, name) VALUES ('metalpowder', 'Metal Powder');
INSERT INTO Item (id, name) VALUES ('metronome', 'Metronome');
INSERT INTO Item (id, name) VALUES ('mewniumz', 'Mewnium Z');
INSERT INTO Item (id, name) VALUES ('mewtwonitex', 'Mewtwonite X');
INSERT INTO Item (id, name) VALUES ('mewtwonitey', 'Mewtwonite Y');
INSERT INTO Item (id, name) VALUES ('micleberry', 'Micle Berry');
INSERT INTO Item (id, name) VALUES ('mimikiumz', 'Mimikium Z');
INSERT INTO Item (id, name) VALUES ('mindplate', 'Mind Plate');
INSERT INTO Item (id, name) VALUES ('miracleseed', 'Miracle Seed');
INSERT INTO Item (id, name) VALUES ('mirrorherb', 'Mirror Herb');
INSERT INTO Item (id, name) VALUES ('mistyseed', 'Misty Seed');
INSERT INTO Item (id, name) VALUES ('moonball', 'Moon Ball');
INSERT INTO Item (id, name) VALUES ('moonstone', 'Moon Stone');
INSERT INTO Item (id, name) VALUES ('muscleband', 'Muscle Band');
INSERT INTO Item (id, name) VALUES ('mysticwater', 'Mystic Water');
INSERT INTO Item (id, name) VALUES ('nanabberry', 'Nanab Berry');
INSERT INTO Item (id, name) VALUES ('nestball', 'Nest Ball');
INSERT INTO Item (id, name) VALUES ('netball', 'Net Ball');
INSERT INTO Item (id, name) VALUES ('nevermeltice', 'Never-Melt Ice');
INSERT INTO Item (id, name) VALUES ('nomelberry', 'Nomel Berry');
INSERT INTO Item (id, name) VALUES ('normalgem', 'Normal Gem');
INSERT INTO Item (id, name) VALUES ('normaliumz', 'Normalium Z');
INSERT INTO Item (id, name) VALUES ('occaberry', 'Occa Berry');
INSERT INTO Item (id, name) VALUES ('oddincense', 'Odd Incense');
INSERT INTO Item (id, name) VALUES ('oldamber', 'Old Amber');
INSERT INTO Item (id, name) VALUES ('oranberry', 'Oran Berry');
INSERT INTO Item (id, name) VALUES ('ovalstone', 'Oval Stone');
INSERT INTO Item (id, name) VALUES ('pamtreberry', 'Pamtre Berry');
INSERT INTO Item (id, name) VALUES ('parkball', 'Park Ball');
INSERT INTO Item (id, name) VALUES ('passhoberry', 'Passho Berry');
INSERT INTO Item (id, name) VALUES ('payapaberry', 'Payapa Berry');
INSERT INTO Item (id, name) VALUES ('pechaberry', 'Pecha Berry');
INSERT INTO Item (id, name) VALUES ('persimberry', 'Persim Berry');
INSERT INTO Item (id, name) VALUES ('petayaberry', 'Petaya Berry');
INSERT INTO Item (id, name) VALUES ('pidgeotite', 'Pidgeotite');
INSERT INTO Item (id, name) VALUES ('pikaniumz', 'Pikanium Z');
INSERT INTO Item (id, name) VALUES ('pikashuniumz', 'Pikashunium Z');
INSERT INTO Item (id, name) VALUES ('pinapberry', 'Pinap Berry');
INSERT INTO Item (id, name) VALUES ('pinsirite', 'Pinsirite');
INSERT INTO Item (id, name) VALUES ('pixieplate', 'Pixie Plate');
INSERT INTO Item (id, name) VALUES ('plumefossil', 'Plume Fossil');
INSERT INTO Item (id, name) VALUES ('poisonbarb', 'Poison Barb');
INSERT INTO Item (id, name) VALUES ('poisongem', 'Poison Gem');
INSERT INTO Item (id, name) VALUES ('poisonmemory', 'Poison Memory');
INSERT INTO Item (id, name) VALUES ('poisoniumz', 'Poisonium Z');
INSERT INTO Item (id, name) VALUES ('pokeball', 'Poke Ball');
INSERT INTO Item (id, name) VALUES ('pomegberry', 'Pomeg Berry');
INSERT INTO Item (id, name) VALUES ('poweranklet', 'Power Anklet');
INSERT INTO Item (id, name) VALUES ('powerband', 'Power Band');
INSERT INTO Item (id, name) VALUES ('powerbelt', 'Power Belt');
INSERT INTO Item (id, name) VALUES ('powerbracer', 'Power Bracer');
INSERT INTO Item (id, name) VALUES ('powerherb', 'Power Herb');
INSERT INTO Item (id, name) VALUES ('powerlens', 'Power Lens');
INSERT INTO Item (id, name) VALUES ('powerweight', 'Power Weight');
INSERT INTO Item (id, name) VALUES ('premierball', 'Premier Ball');
INSERT INTO Item (id, name) VALUES ('primariumz', 'Primarium Z');
INSERT INTO Item (id, name) VALUES ('prismscale', 'Prism Scale');
INSERT INTO Item (id, name) VALUES ('protectivepads', 'Protective Pads');
INSERT INTO Item (id, name) VALUES ('protector', 'Protector');
INSERT INTO Item (id, name) VALUES ('psychicgem', 'Psychic Gem');
INSERT INTO Item (id, name) VALUES ('psychicmemory', 'Psychic Memory');
INSERT INTO Item (id, name) VALUES ('psychicseed', 'Psychic Seed');
INSERT INTO Item (id, name) VALUES ('psychiumz', 'Psychium Z');
INSERT INTO Item (id, name) VALUES ('punchingglove', 'Punching Glove');
INSERT INTO Item (id, name) VALUES ('qualotberry', 'Qualot Berry');
INSERT INTO Item (id, name) VALUES ('quickball', 'Quick Ball');
INSERT INTO Item (id, name) VALUES ('quickclaw', 'Quick Claw');
INSERT INTO Item (id, name) VALUES ('quickpowder', 'Quick Powder');
INSERT INTO Item (id, name) VALUES ('rabutaberry', 'Rabuta Berry');
INSERT INTO Item (id, name) VALUES ('rarebone', 'Rare Bone');
INSERT INTO Item (id, name) VALUES ('rawstberry', 'Rawst Berry');
INSERT INTO Item (id, name) VALUES ('razorclaw', 'Razor Claw');
INSERT INTO Item (id, name) VALUES ('razorfang', 'Razor Fang');
INSERT INTO Item (id, name) VALUES ('razzberry', 'Razz Berry');
INSERT INTO Item (id, name) VALUES ('reapercloth', 'Reaper Cloth');
INSERT INTO Item (id, name) VALUES ('redcard', 'Red Card');
INSERT INTO Item (id, name) VALUES ('redorb', 'Red Orb');
INSERT INTO Item (id, name) VALUES ('repeatball', 'Repeat Ball');
INSERT INTO Item (id, name) VALUES ('ribbonsweet', 'Ribbon Sweet');
INSERT INTO Item (id, name) VALUES ('rindoberry', 'Rindo Berry');
INSERT INTO Item (id, name) VALUES ('ringtarget', 'Ring Target');
INSERT INTO Item (id, name) VALUES ('rockgem', 'Rock Gem');
INSERT INTO Item (id, name) VALUES ('rockincense', 'Rock Incense');
INSERT INTO Item (id, name) VALUES ('rockmemory', 'Rock Memory');
INSERT INTO Item (id, name) VALUES ('rockiumz', 'Rockium Z');
INSERT INTO Item (id, name) VALUES ('rockyhelmet', 'Rocky Helmet');
INSERT INTO Item (id, name) VALUES ('roomservice', 'Room Service');
INSERT INTO Item (id, name) VALUES ('rootfossil', 'Root Fossil');
INSERT INTO Item (id, name) VALUES ('roseincense', 'Rose Incense');
INSERT INTO Item (id, name) VALUES ('roseliberry', 'Roseli Berry');
INSERT INTO Item (id, name) VALUES ('rowapberry', 'Rowap Berry');
INSERT INTO Item (id, name) VALUES ('rustedshield', 'Rusted Shield');
INSERT INTO Item (id, name) VALUES ('rustedsword', 'Rusted Sword');
INSERT INTO Item (id, name) VALUES ('sablenite', 'Sablenite');
INSERT INTO Item (id, name) VALUES ('sachet', 'Sachet');
INSERT INTO Item (id, name) VALUES ('safariball', 'Safari Ball');
INSERT INTO Item (id, name) VALUES ('safetygoggles', 'Safety Goggles');
INSERT INTO Item (id, name) VALUES ('sailfossil', 'Sail Fossil');
INSERT INTO Item (id, name) VALUES ('salacberry', 'Salac Berry');
INSERT INTO Item (id, name) VALUES ('salamencite', 'Salamencite');
INSERT INTO Item (id, name) VALUES ('sceptilite', 'Sceptilite');
INSERT INTO Item (id, name) VALUES ('scizorite', 'Scizorite');
INSERT INTO Item (id, name) VALUES ('scopelens', 'Scope Lens');
INSERT INTO Item (id, name) VALUES ('seaincense', 'Sea Incense');
INSERT INTO Item (id, name) VALUES ('sharpbeak', 'Sharp Beak');
INSERT INTO Item (id, name) VALUES ('sharpedonite', 'Sharpedonite');
INSERT INTO Item (id, name) VALUES ('shedshell', 'Shed Shell');
INSERT INTO Item (id, name) VALUES ('shellbell', 'Shell Bell');
INSERT INTO Item (id, name) VALUES ('shinystone', 'Shiny Stone');
INSERT INTO Item (id, name) VALUES ('shockdrive', 'Shock Drive');
INSERT INTO Item (id, name) VALUES ('shucaberry', 'Shuca Berry');
INSERT INTO Item (id, name) VALUES ('silkscarf', 'Silk Scarf');
INSERT INTO Item (id, name) VALUES ('silverpowder', 'Silver Powder');
INSERT INTO Item (id, name) VALUES ('sitrusberry', 'Sitrus Berry');
INSERT INTO Item (id, name) VALUES ('skullfossil', 'Skull Fossil');
INSERT INTO Item (id, name) VALUES ('skyplate', 'Sky Plate');
INSERT INTO Item (id, name) VALUES ('slowbronite', 'Slowbronite');
INSERT INTO Item (id, name) VALUES ('smoothrock', 'Smooth Rock');
INSERT INTO Item (id, name) VALUES ('snorliumz', 'Snorlium Z');
INSERT INTO Item (id, name) VALUES ('snowball', 'Snowball');
INSERT INTO Item (id, name) VALUES ('softsand', 'Soft Sand');
INSERT INTO Item (id, name) VALUES ('solganiumz', 'Solganium Z');
INSERT INTO Item (id, name) VALUES ('souldew', 'Soul Dew');
INSERT INTO Item (id, name) VALUES ('spelltag', 'Spell Tag');
INSERT INTO Item (id, name) VALUES ('spelonberry', 'Spelon Berry');
INSERT INTO Item (id, name) VALUES ('splashplate', 'Splash Plate');
INSERT INTO Item (id, name) VALUES ('spookyplate', 'Spooky Plate');
INSERT INTO Item (id, name) VALUES ('sportball', 'Sport Ball');
INSERT INTO Item (id, name) VALUES ('starfberry', 'Starf Berry');
INSERT INTO Item (id, name) VALUES ('starsweet', 'Star Sweet');
INSERT INTO Item (id, name) VALUES ('steelixite', 'Steelixite');
INSERT INTO Item (id, name) VALUES ('steelgem', 'Steel Gem');
INSERT INTO Item (id, name) VALUES ('steelmemory', 'Steel Memory');
INSERT INTO Item (id, name) VALUES ('steeliumz', 'Steelium Z');
INSERT INTO Item (id, name) VALUES ('stick', 'Stick');
INSERT INTO Item (id, name) VALUES ('stickybarb', 'Sticky Barb');
INSERT INTO Item (id, name) VALUES ('stoneplate', 'Stone Plate');
INSERT INTO Item (id, name) VALUES ('strangeball', 'Strange Ball');
INSERT INTO Item (id, name) VALUES ('strawberrysweet', 'Strawberry Sweet');
INSERT INTO Item (id, name) VALUES ('sunstone', 'Sun Stone');
INSERT INTO Item (id, name) VALUES ('swampertite', 'Swampertite');
INSERT INTO Item (id, name) VALUES ('sweetapple', 'Sweet Apple');
INSERT INTO Item (id, name) VALUES ('syrupyapple', 'Syrupy Apple');
INSERT INTO Item (id, name) VALUES ('tamatoberry', 'Tamato Berry');
INSERT INTO Item (id, name) VALUES ('tangaberry', 'Tanga Berry');
INSERT INTO Item (id, name) VALUES ('tapuniumz', 'Tapunium Z');
INSERT INTO Item (id, name) VALUES ('tartapple', 'Tart Apple');
INSERT INTO Item (id, name) VALUES ('terrainextender', 'Terrain Extender');
INSERT INTO Item (id, name) VALUES ('thickclub', 'Thick Club');
INSERT INTO Item (id, name) VALUES ('throatspray', 'Throat Spray');
INSERT INTO Item (id, name) VALUES ('thunderstone', 'Thunder Stone');
INSERT INTO Item (id, name) VALUES ('timerball', 'Timer Ball');
INSERT INTO Item (id, name) VALUES ('toxicorb', 'Toxic Orb');
INSERT INTO Item (id, name) VALUES ('toxicplate', 'Toxic Plate');
INSERT INTO Item (id, name) VALUES ('tr00', 'TR00');
INSERT INTO Item (id, name) VALUES ('tr01', 'TR01');
INSERT INTO Item (id, name) VALUES ('tr02', 'TR02');
INSERT INTO Item (id, name) VALUES ('tr03', 'TR03');
INSERT INTO Item (id, name) VALUES ('tr04', 'TR04');
INSERT INTO Item (id, name) VALUES ('tr05', 'TR05');
INSERT INTO Item (id, name) VALUES ('tr06', 'TR06');
INSERT INTO Item (id, name) VALUES ('tr07', 'TR07');
INSERT INTO Item (id, name) VALUES ('tr08', 'TR08');
INSERT INTO Item (id, name) VALUES ('tr09', 'TR09');
INSERT INTO Item (id, name) VALUES ('tr10', 'TR10');
INSERT INTO Item (id, name) VALUES ('tr11', 'TR11');
INSERT INTO Item (id, name) VALUES ('tr12', 'TR12');
INSERT INTO Item (id, name) VALUES ('tr13', 'TR13');
INSERT INTO Item (id, name) VALUES ('tr14', 'TR14');
INSERT INTO Item (id, name) VALUES ('tr15', 'TR15');
INSERT INTO Item (id, name) VALUES ('tr16', 'TR16');
INSERT INTO Item (id, name) VALUES ('tr17', 'TR17');
INSERT INTO Item (id, name) VALUES ('tr18', 'TR18');
INSERT INTO Item (id, name) VALUES ('tr19', 'TR19');
INSERT INTO Item (id, name) VALUES ('tr20', 'TR20');
INSERT INTO Item (id, name) VALUES ('tr21', 'TR21');
INSERT INTO Item (id, name) VALUES ('tr22', 'TR22');
INSERT INTO Item (id, name) VALUES ('tr23', 'TR23');
INSERT INTO Item (id, name) VALUES ('tr24', 'TR24');
INSERT INTO Item (id, name) VALUES ('tr25', 'TR25');
INSERT INTO Item (id, name) VALUES ('tr26', 'TR26');
INSERT INTO Item (id, name) VALUES ('tr27', 'TR27');
INSERT INTO Item (id, name) VALUES ('tr28', 'TR28');
INSERT INTO Item (id, name) VALUES ('tr29', 'TR29');
INSERT INTO Item (id, name) VALUES ('tr30', 'TR30');
INSERT INTO Item (id, name) VALUES ('tr31', 'TR31');
INSERT INTO Item (id, name) VALUES ('tr32', 'TR32');
INSERT INTO Item (id, name) VALUES ('tr33', 'TR33');
INSERT INTO Item (id, name) VALUES ('tr34', 'TR34');
INSERT INTO Item (id, name) VALUES ('tr35', 'TR35');
INSERT INTO Item (id, name) VALUES ('tr36', 'TR36');
INSERT INTO Item (id, name) VALUES ('tr37', 'TR37');
INSERT INTO Item (id, name) VALUES ('tr38', 'TR38');
INSERT INTO Item (id, name) VALUES ('tr39', 'TR39');
INSERT INTO Item (id, name) VALUES ('tr40', 'TR40');
INSERT INTO Item (id, name) VALUES ('tr41', 'TR41');
INSERT INTO Item (id, name) VALUES ('tr42', 'TR42');
INSERT INTO Item (id, name) VALUES ('tr43', 'TR43');
INSERT INTO Item (id, name) VALUES ('tr44', 'TR44');
INSERT INTO Item (id, name) VALUES ('tr45', 'TR45');
INSERT INTO Item (id, name) VALUES ('tr46', 'TR46');
INSERT INTO Item (id, name) VALUES ('tr47', 'TR47');
INSERT INTO Item (id, name) VALUES ('tr48', 'TR48');
INSERT INTO Item (id, name) VALUES ('tr49', 'TR49');
INSERT INTO Item (id, name) VALUES ('tr50', 'TR50');
INSERT INTO Item (id, name) VALUES ('tr51', 'TR51');
INSERT INTO Item (id, name) VALUES ('tr52', 'TR52');
INSERT INTO Item (id, name) VALUES ('tr53', 'TR53');
INSERT INTO Item (id, name) VALUES ('tr54', 'TR54');
INSERT INTO Item (id, name) VALUES ('tr55', 'TR55');
INSERT INTO Item (id, name) VALUES ('tr56', 'TR56');
INSERT INTO Item (id, name) VALUES ('tr57', 'TR57');
INSERT INTO Item (id, name) VALUES ('tr58', 'TR58');
INSERT INTO Item (id, name) VALUES ('tr59', 'TR59');
INSERT INTO Item (id, name) VALUES ('tr60', 'TR60');
INSERT INTO Item (id, name) VALUES ('tr61', 'TR61');
INSERT INTO Item (id, name) VALUES ('tr62', 'TR62');
INSERT INTO Item (id, name) VALUES ('tr63', 'TR63');
INSERT INTO Item (id, name) VALUES ('tr64', 'TR64');
INSERT INTO Item (id, name) VALUES ('tr65', 'TR65');
INSERT INTO Item (id, name) VALUES ('tr66', 'TR66');
INSERT INTO Item (id, name) VALUES ('tr67', 'TR67');
INSERT INTO Item (id, name) VALUES ('tr68', 'TR68');
INSERT INTO Item (id, name) VALUES ('tr69', 'TR69');
INSERT INTO Item (id, name) VALUES ('tr70', 'TR70');
INSERT INTO Item (id, name) VALUES ('tr71', 'TR71');
INSERT INTO Item (id, name) VALUES ('tr72', 'TR72');
INSERT INTO Item (id, name) VALUES ('tr73', 'TR73');
INSERT INTO Item (id, name) VALUES ('tr74', 'TR74');
INSERT INTO Item (id, name) VALUES ('tr75', 'TR75');
INSERT INTO Item (id, name) VALUES ('tr76', 'TR76');
INSERT INTO Item (id, name) VALUES ('tr77', 'TR77');
INSERT INTO Item (id, name) VALUES ('tr78', 'TR78');
INSERT INTO Item (id, name) VALUES ('tr79', 'TR79');
INSERT INTO Item (id, name) VALUES ('tr80', 'TR80');
INSERT INTO Item (id, name) VALUES ('tr81', 'TR81');
INSERT INTO Item (id, name) VALUES ('tr82', 'TR82');
INSERT INTO Item (id, name) VALUES ('tr83', 'TR83');
INSERT INTO Item (id, name) VALUES ('tr84', 'TR84');
INSERT INTO Item (id, name) VALUES ('tr85', 'TR85');
INSERT INTO Item (id, name) VALUES ('tr86', 'TR86');
INSERT INTO Item (id, name) VALUES ('tr87', 'TR87');
INSERT INTO Item (id, name) VALUES ('tr88', 'TR88');
INSERT INTO Item (id, name) VALUES ('tr89', 'TR89');
INSERT INTO Item (id, name) VALUES ('tr90', 'TR90');
INSERT INTO Item (id, name) VALUES ('tr91', 'TR91');
INSERT INTO Item (id, name) VALUES ('tr92', 'TR92');
INSERT INTO Item (id, name) VALUES ('tr93', 'TR93');
INSERT INTO Item (id, name) VALUES ('tr94', 'TR94');
INSERT INTO Item (id, name) VALUES ('tr95', 'TR95');
INSERT INTO Item (id, name) VALUES ('tr96', 'TR96');
INSERT INTO Item (id, name) VALUES ('tr97', 'TR97');
INSERT INTO Item (id, name) VALUES ('tr98', 'TR98');
INSERT INTO Item (id, name) VALUES ('tr99', 'TR99');
INSERT INTO Item (id, name) VALUES ('twistedspoon', 'Twisted Spoon');
INSERT INTO Item (id, name) VALUES ('tyranitarite', 'Tyranitarite');
INSERT INTO Item (id, name) VALUES ('ultraball', 'Ultra Ball');
INSERT INTO Item (id, name) VALUES ('ultranecroziumz', 'Ultranecrozium Z');
INSERT INTO Item (id, name) VALUES ('unremarkableteacup', 'Unremarkable Teacup');
INSERT INTO Item (id, name) VALUES ('upgrade', 'Up-Grade');
INSERT INTO Item (id, name) VALUES ('utilityumbrella', 'Utility Umbrella');
INSERT INTO Item (id, name) VALUES ('venusaurite', 'Venusaurite');
INSERT INTO Item (id, name) VALUES ('wacanberry', 'Wacan Berry');
INSERT INTO Item (id, name) VALUES ('watergem', 'Water Gem');
INSERT INTO Item (id, name) VALUES ('watermemory', 'Water Memory');
INSERT INTO Item (id, name) VALUES ('waterstone', 'Water Stone');
INSERT INTO Item (id, name) VALUES ('wateriumz', 'Waterium Z');
INSERT INTO Item (id, name) VALUES ('watmelberry', 'Watmel Berry');
INSERT INTO Item (id, name) VALUES ('waveincense', 'Wave Incense');
INSERT INTO Item (id, name) VALUES ('weaknesspolicy', 'Weakness Policy');
INSERT INTO Item (id, name) VALUES ('wellspringmask', 'Wellspring Mask');
INSERT INTO Item (id, name) VALUES ('wepearberry', 'Wepear Berry');
INSERT INTO Item (id, name) VALUES ('whippeddream', 'Whipped Dream');
INSERT INTO Item (id, name) VALUES ('whiteherb', 'White Herb');
INSERT INTO Item (id, name) VALUES ('widelens', 'Wide Lens');
INSERT INTO Item (id, name) VALUES ('wikiberry', 'Wiki Berry');
INSERT INTO Item (id, name) VALUES ('wiseglasses', 'Wise Glasses');
INSERT INTO Item (id, name) VALUES ('yacheberry', 'Yache Berry');
INSERT INTO Item (id, name) VALUES ('zapplate', 'Zap Plate');
INSERT INTO Item (id, name) VALUES ('zoomlens', 'Zoom Lens');
INSERT INTO Item (id, name) VALUES ('berserkgene', 'Berserk Gene');
INSERT INTO Item (id, name) VALUES ('berry', 'Berry');
INSERT INTO Item (id, name) VALUES ('bitterberry', 'Bitter Berry');
INSERT INTO Item (id, name) VALUES ('burntberry', 'Burnt Berry');
INSERT INTO Item (id, name) VALUES ('goldberry', 'Gold Berry');
INSERT INTO Item (id, name) VALUES ('iceberry', 'Ice Berry');
INSERT INTO Item (id, name) VALUES ('mintberry', 'Mint Berry');
INSERT INTO Item (id, name) VALUES ('miracleberry', 'Miracle Berry');
INSERT INTO Item (id, name) VALUES ('mysteryberry', 'Mystery Berry');
INSERT INTO Item (id, name) VALUES ('pinkbow', 'Pink Bow');
INSERT INTO Item (id, name) VALUES ('polkadotbow', 'Polkadot Bow');
INSERT INTO Item (id, name) VALUES ('przcureberry', 'PRZ Cure Berry');
INSERT INTO Item (id, name) VALUES ('psncureberry', 'PSN Cure Berry');
INSERT INTO Item (id, name) VALUES ('crucibellite', 'Crucibellite');
INSERT INTO Item (id, name) VALUES ('vilevial', 'Vile Vial');
